name: "Terraform-Apply-Infra-Release"
on:
  workflow_dispatch:
    inputs:
      client:
        description: 'client name'
        required: true
        type: choice
        options:
        - 'pepsi'
        - 'coke'
        default: 'pepsi'
      env:
        description: 'environment'
        required: true
        type: choice
        options:
        - 'production'
        - 'staging'
        default: 'production'
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "terraform/workspaces/pepsi/"    

    steps:
      - name: Checkout
        uses: actions/checkout@v2        

      
