name: "Terraform-Apply-Infra-Release"
on:
  workflow_dispatch:
    inputs:
      client:
        description: 'client name'
        required: true
        type: choice
        options:
        - 'pepsi'
        - 'coke'
        default: 'pepsi'
      env:
        description: 'environment'
        required: true
        type: choice
        options:
        - 'production'
        - 'staging'
        default: 'production'
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Input Variables
        shell: bash
        run: |
          echo "${{ github.event.inputs.client }}"
          echo "${{ github.event.inputs.env }}"
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "terraform/workspaces/${{ github.event.inputs.client }}/"    
    steps:
      - name: Checkout
        uses: actions/checkout@v2 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TER_CLOUD_API_TOKEN }}

      - name: Terraform Init
        id: init        
        run: |            
            terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform fmt
          terraform plan 
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply and Destroy
         
        run: | 
             terraform apply -auto-approve
             terraform destroy -auto-approve
             
             

      
