name: "Terraform-Apply-Infra-Release"
on:
  workflow_dispatch:
    inputs:
      client:
        description: 'Client Name'
        required: true
        type: choice
        options:
        - 'pepsi'
        - 'coke'
      Env:
        description: 'Environment'
        required: true
        type: choice
        options:
        - 'production'
        - 'Staging'
        default: 'production'
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "terraform/workspaces/pepsi/"    

    steps:
      - name: Checkout
        uses: actions/checkout@v2        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TER_CLOUD_API_TOKEN }}

      - name: Terraform Init
        id: init        
        run: |            
            terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: |
          terraform fmt
          terraform plan 
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |              
          terraform apply -auto-approve
